apiVersion: interfaces.eda.nokia.com/v1alpha1
kind: Interface
metadata:
  name: leaf1-leaf2-simple-mh-lag
  namespace: eda
  labels:
    eda.nokia.com/role: edge
spec:
  type: lag
  description: "Customer facing multihoming lag"
  enabled: true
  mtu: 9000
  lag:
    type: lacp
    minLinks: 2
    multihoming:
      mode: all-active
      preferredActiveNode: leaf1
      revertive: true
    lacp:
      mode: active
      interval: fast
      systemPriority: 32768
  members:
    - node: leaf1
      interface: ethernet-1-20
    - node: leaf2
      interface: ethernet-1-20
