apiVersion: fabrics.eda.nokia.com/v1
kind: FabricTopology
metadata:
  name: 2tier-200g
  namespace: eda
spec:
  operation: Reconcile
  #########################
  #### Node Templates #####
  #########################
  nodeTemplates:
    - name: leaf
      nodeProfile: srlinux-ghcr-26.3.1
      platform: 7220 IXR-D2L
    - name: spine
      nodeProfile: srlinux-ghcr-26.3.1
      platform: 7220 IXR-D3L
  #########################
  ## Edge Link Templates ##
  #########################
  edgeLinkTemplates:
    - name: compute
      type: ESLAG
      encapType: Dot1q
      nodesInLAG: 2
  #################################
  ## Inter Switch Link Templates ##
  #################################
  interSwitchLinkTemplates:
    - name: d3l-leaf-spine-isl
      type: InterSwitch
      speed: 100G
      encapType: "Null"
  #########################
  #### Pod Templates #####
  #########################
  podTemplates:
    - name: leaf-spine-pod
      nodeGroups:
        - name: leaf
          nodeName: '{{.podName}}-leaf{{ printf "%02d" .nodeIndex }}'
          nodeTemplate: leaf
          count: 4
        - name: spine
          nodeName: '{{.podName}}-spine{{printf "%02d" .nodeIndex}}'
          nodeTemplate: spine
          count: 2
      ##############################
      ## Inter Switch Link Groups ##
      ##############################
      interSwitchLinkGroups:
        - name: leaf-spine
          template: d3l-leaf-spine-isl
          interfacesPerNodePair: 2
          localNodes:
            nodeSelectors:
              - eda.nokia.com/role=leaf
            interfaceStartIndex: "1-53"
          remoteNodes:
            nodeSelectors:
              - eda.nokia.com/role=spine
            interfaceStartIndex: "1-1"
      ##############################
      ###### Edge Link Groups ######
      ##############################
      edgeLinkGroups:
        - name: compute
          template: compute
          localNodes:
            nodeSelectors:
              - eda.nokia.com/role=leaf
          count: 30
  ###############
  #### Pods #####
  ###############
  pods:
    - name: pod1
      podTemplate: leaf-spine-pod
