apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: vmware-plugin
  namespace: eda-system
spec:
  operation: install
  apps:
    - app: vmware-plugin
      catalog: eda-catalog-builtin-apps
      vendor: nokia
      version:
        type: semver
        value: v3.0.0
  type: app-installer
