apiVersion: fabrics.eda.nokia.com/v1alpha1
kind: Fabric
metadata:
  name: my-fabric
spec:
  leafNodeSelector:
    - eda.nokia.com/role=leaf
  linkSelector:
    - eda.nokia.com/role=interSwitch
  spineNodeSelector:
    - eda.nokia.com/role=spine
  systemPoolIPV4: systemipv4-pool
  islPoolIPV4: ipv4-pool
  underlayProtocol:
    asnPool: asn-pool
    protocol:
      - ebgp
  overlayProtocol:
    protocol: ebgp
