apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: environment
spec:
  group: environment.eda.nokia.com
  version: v1
  title: Environment
  description: |
    This application provides workflows for environment configuration.

    It deploys CLI plugins and environment files to targets.
  image: ghcr.io/nokia-eda/apps/environment:v6.999.0
  gitReference: 1da44402c90fbeba1161ccb8ea3350ef0353843d
  author: Nokia
  supportedEndpoints:
    - "srl:24.10.*"
    - "srl:25.3.*"
    - "srl:25.7.*"
    - "srl:25.10.*"
    - "srl:26.3.*"
    - "sros:24.10.r4+"
    - "sros:25.3.r2+"
    - "sros:25.7.*"
    - "sros:25.10.*"
    - "sros:26.3.*"
    - "eos:4.33.2f:beta"
    - "nxos:10.5.2:alpha"
  supportedCoreVersions:
    - "v5.0"
  appInfo:
    documentation: environment/docs
    categories:
      - "core"
  components:
    - cr:
        path: environment/workflows/cliplugin/core_v1_flowdefinition.yaml
    - cr:
        path: environment/workflows/env/core_v1_flowdefinition.yaml
    - crd:
        api:
          expose: readWrite
        namespaced: true
        path: environment/crds/environment.eda.nokia.com_setupenvs.yaml
        schema: environment/openapiv3/eda_oas_environment.eda.nokia.com_setupenvs.json
        workflow: true
        ui:
          name: Push Environment
        conversionScript: environment/intents/setupenv/conversion_v1.py
    - crd:
        api:
          expose: readWrite
        namespaced: true
        path: environment/crds/environment.eda.nokia.com_cliplugins.yaml
        schema: environment/openapiv3/eda_oas_environment.eda.nokia.com_cliplugins.json
        workflow: true
        ui:
          name: Push CLI Plugin
        conversionScript: environment/intents/cliplugin/conversion_v1.py
  dependencies:
    - file:
        path: environment/api
    - file:
        path: environment/api/v1/pysrc
