apiVersion: services.eda.nokia.com/v1alpha1
kind: VirtualNetwork
metadata:
  name: vnet1
  namespace: eda
spec:
  bridgeDomains:
    - name: bd1
      spec:
        eviPool: evi-pool
        l2proxyARPND:
          dynamicLearning:
            ageTime: 2000
            enabled: true
            sendRefresh: 2000
          ipDuplication:
            enabled: true
            holdDownTime: 10
            monitoringWindow: 10
            numMoves: 4
          proxyARP: true
          proxyND: false
          tableSize: 250
        macAging: 300
        tunnelIndexPool: tunnel-index-pool
        type: EVPNVXLAN
        vniPool: vni-pool
  vlans:
    - name: storage
      spec:
        bridgeDomain: bd1
        interfaceSelector:
          - eda.nokia.com/edgeLinkType=storage
        vlanID: pool
        vlanPool: vlan-pool
    - name: compute
      spec:
        bridgeDomain: bd1
        interfaceSelector:
          - eda.nokia.com/edgeLinkType=compute
        vlanID: pool
        vlanPool: vlan-pool
