apiVersion: interfaces.eda.nokia.com/v1
kind: Interface
metadata:
  labels:
    eda.nokia.com/role: interSwitch
  name: leaf-1-ethernet-1-2
  namespace: eda
spec:
  enabled: true
  encapType: 'Null'
  ethernet:
    stormControl: {}
  lldp: true
  members:
    - enabled: true
      interface: ethernet-1-2
      lacpPortPriority: 32768
      node: leaf-1
  type: Interface