apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: notifier-install
  namespace: eda-system
spec:
  type: app-installer
  input:
    app: notifier
    catalog: eda-catalog-builtin-apps
    operation: install
    vendor: nokia
    version:
      type: semver
      value: v2.0.0
