apiVersion: appstore.eda.nokia.com/v1
kind: AppInstaller
metadata:
  name: notifier-install
  namespace: eda-system
spec:
  operation: install
  apps:
    - appId: notifier.eda.nokia.com
      catalog: eda-catalog-builtin-apps
      version:
        value: v4.0.0
