apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: aaa
spec:
  group: aaa.eda.nokia.com
  version: v1
  title: AAA
  description: |
    This application provides functionality relating to authentication, authorization, and accounting.

    It allows the deployment of users, groups, and AAA policy, performing any alarming as necessary.
  image: ghcr.io/nokia-eda/apps/aaa:v6.999.0
  gitReference: 1da44402c90fbeba1161ccb8ea3350ef0353843d
  gitPathPrefix: /
  author: nokia
  supportedEndpoints:
    - "srl:24.10.*"
    - "srl:25.3.*"
    - "srl:25.7.*"
    - "srl:25.10.*"
    - "srl:26.3.*"
    - "sros:24.10.r4+"
    - "sros:25.3.r2+"
    - "sros:25.7.*"
    - "sros:25.10.*"
    - "sros:26.3.*"
    - "eos:4.33.2f:beta"
    - "nxos:10.5.2:alpha"
  supportedCoreVersions:
    - "v5.0"
  appInfo:
    categories:
      - "system"
    documentation: aaa/docs
  components:
    - crd:
        path: aaa/crds/aaa.eda.nokia.com_userdeployments.yaml
        schema: aaa/openapiv3/eda_oas_aaa.eda.nokia.com_userdeployments.json
        api:
          expose: none
        namespaced: false
        conversionScript: aaa/intents/userdeployment/conversion_v1.py
    - crd:
        path: aaa/crds/aaa.eda.nokia.com_nodegroupdeployments.yaml
        schema: aaa/openapiv3/eda_oas_aaa.eda.nokia.com_nodegroupdeployments.json
        conversionScript: aaa/intents/nodegroupdeployment/conversion_v1.py
    - crd:
        path: aaa/crds/aaa.eda.nokia.com_nodegroups.yaml
        schema: aaa/openapiv3/eda_oas_aaa.eda.nokia.com_nodegroups.json
        ui:
          category: AAA
          name: Node User Groups
          icon: AdminSettings
          # panel: system_administration
        api:
          expose: readWrite
        conversionScript: aaa/intents/nodegroup/conversion_v1.py
    - crd:
        path: aaa/crds/aaa.eda.nokia.com_nodeuserstates.yaml
        schema: aaa/openapiv3/eda_oas_aaa.eda.nokia.com_nodeuserstates.json
        conversionScript: aaa/intents/nodeuserstate/conversion_v1.py
    - cr:
        path: aaa/resources/default.yaml
    - cr:
        path: aaa/resources/engine_v1_nodegroup_sudo.yaml
    - script:
        path: aaa/intents/userdeployment/userdeployment.py
        type: config
        trigger:
          kind: UserDeployment
    - script:
        path: aaa/intents/nodeuserstate/nodeuserstate_intent.py
        type: state
        trigger:
          kind: NodeUserState
    - script:
        path: aaa/intents/nodegroupdeployment/nodegroupdeployment_intent.py
        type: config
        trigger:
          kind: NodeGroupDeployment
          # - script:
          #     path: core/userdeploymentstate.py
          #     type: state
          #     trigger:
          #       kind: UserDeploymentState
    - crd:
        api:
          expose: readWrite
        path: aaa/crds/aaa.eda.nokia.com_servergroups.yaml
        schema: aaa/openapiv3/eda_oas_aaa.eda.nokia.com_servergroups.json
        ui:
          category: AAA
          name: Server Groups
          icon: DatabaseAuthentication
    - script:
        path: aaa/intents/servergroup/servergroup_intent.py
        trigger:
          kind: ServerGroup
        type: config
    - crd:
        api:
          expose: readWrite
        path: aaa/crds/aaa.eda.nokia.com_servergroupstates.yaml
        schema: aaa/openapiv3/eda_oas_aaa.eda.nokia.com_servergroupstates.json
    - script:
        path: aaa/intents/servergroupstate/servergroupstate_intent.py
        trigger:
          kind: ServerGroupState
        type: state
    - crd:
        api:
          expose: readWrite
        path: aaa/crds/aaa.eda.nokia.com_authenticationpolicies.yaml
        schema: aaa/openapiv3/eda_oas_aaa.eda.nokia.com_authenticationpolicies.json
        ui:
          category: AAA
          name: Authentication Policies
          icon: Security
    - script:
        path: aaa/intents/authenticationpolicy/authenticationpolicy_intent.py
        trigger:
          kind: AuthenticationPolicy
        type: config
    - cr:
        path: aaa/alarms/alarms.yaml
    - crd:
        api:
          expose: readWrite
        path: aaa/crds/aaa.eda.nokia.com_authenticationpolicystates.yaml
        schema: aaa/openapiv3/eda_oas_aaa.eda.nokia.com_authenticationpolicystates.json
    - script:
        path: aaa/intents/authenticationpolicystate/authenticationpolicystate_intent.py
        trigger:
          kind: AuthenticationPolicyState
        type: state
  dependencies:
    - file:
        path: common/
    - file:
        path: utils/
    - file:
        path: aaa/intents
    - file:
        path: core/pysrc/
    - file:
        path: aaa/api
    - file:
        path: aaa/api/v1/pysrc
    - file:
        path: aaa/intents/servergroupstate/common.py
    - file:
        path: aaa/alarms/pysrc
    - file:
        path: aaa/intents/common/common.py
