apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: demo
spec:
  group: demo.eda.nokia.com
  version: v1alpha1
  title: Demo
  description: |
    This application provides demonstration examples
  image: ghcr.io/nokia-eda/apps/demo:v6.999.0
  gitReference: 1da44402c90fbeba1161ccb8ea3350ef0353843d
  gitPathPrefix: /
  author: nokia
  appInfo:
    categories:
      - "demo"
    documentation: demo/docs
    settings: demo/settings/openapi/eda_oas_demo.eda.nokia.com_appsettings.json
  supportedEndpoints:
    - "srl:24.10.*"
    - "srl:25.3.*"
    - "srl:25.7.*"
    - "srl:25.10.*"
    - "srl:26.3.*"
    - "sros:24.10.r4+"
    - "sros:25.3.r2+"
    - "sros:25.7.*"
    - "sros:25.10.*"
    - "sros:26.3.*"
    - "eos:4.33.2f:beta"
    - "nxos:10.5.2:alpha"
  supportedCoreVersions:
    - "v5.0"
  components:
    - crd:
        path: demo/crds/demo.eda.nokia.com_simplevrfs.yaml
        schema: demo/openapiv3/eda_oas_demo.eda.nokia.com_simplevrfs.json
        api:
          expose: readWrite
        ui:
          category: Demo
          name: Simple VRFs
    - crd:
        path: demo/crds/demo.eda.nokia.com_labels.yaml
        schema: demo/openapiv3/eda_oas_demo.eda.nokia.com_labels.json
        api:
          expose: readWrite
        ui:
          category: Demo
          name: Labels
          panel: system_administration
    - crd:
        path: demo/crds/demo.eda.nokia.com_oesextensions.yaml
        schema: demo/openapiv3/eda_oas_demo.eda.nokia.com_oesextensions.json
        api:
          expose: readWrite
        ui:
          category: Demo
          name: OAS Extension
          icon: Extender
    - crd:
        path: demo/crds/demo.eda.nokia.com_overlays.yaml
        schema: demo/openapiv3/eda_oas_demo.eda.nokia.com_overlays.json
        namespaced: false
        api:
          expose: readWrite
    - crd:
        path: demo/crds/demo.eda.nokia.com_gvkpings.yaml
        schema: demo/openapiv3/eda_oas_demo.eda.nokia.com_gvkpings.json
        api:
          expose: readWrite
        ui:
          category: Demo
          name: GVK Ping
    - crd:
        path: demo/crds/demo.eda.nokia.com_k8stypes.yaml
        schema: demo/openapiv3/eda_oas_demo.eda.nokia.com_k8stypes.json
        api:
          expose: readWrite
        ui:
          category: Demo
          name: Kubernetes
    - script:
        path: demo/intents/simplevrf/simplevrf_intent.py
        type: config
        trigger:
          kind: SimpleVRF
    - script:
        path: demo/intents/overlay/overlay_intent.py
        type: state
        trigger:
          kind: Overlay
    - view:
        path: demo/ui/dashboard.json
        ui:
          category: Demo
          name: Extra Views
          panel: system_administration
    - view:
        path: demo/ui/oas_extension.json
        ui:
          category: Demo
          name: OAS Extension
    - panel:
        path: demo/ui/panel.json
        name: Demo
    - cr:
        path: demo/workflows/interfacebounce/core_v1_flowdefinition.yaml
    - cr:
        path: demo/workflows/interfaceupcheck/core_v1_flowdefinition.yaml
  dependencies:
    - file:
        path: common/
    - file:
        path: utils/
    - file:
        path: demo/ui
    - file:
        path: demo/intents
    - file:
        path: demo/api
    - file:
        path: demo/api/v1alpha1/pysrc
