apiVersion: netbox.eda.nokia.com/v1alpha1
kind: Allocation
metadata:
  name: ippool1
  namespace: eda
spec:
  enabled: true
  instance: netbox1  # <-- Reference to the Instance CR above
  tags:
    - eda-pool       # <-- Must match tags on NetBox prefixes
  type: ip-in-subnet # <-- One of: ip-address, subnet, ip-in-subnet