apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: netbox-install
  namespace: eda-system
spec:
  type: app-installer
  input:
    operation: install
    apps:
      - app: netbox
        catalog: eda-catalog-builtin-apps
        vendor: nokia
        version:
          type: semver
          value: v1.0.0
