apiVersion: v1
kind: Secret
metadata:
  name: netbox-webhook-signature
  namespace: eda
type: Opaque
data:
  # base64-encoded HMAC signature key that NetBox will use
  signatureKey: <base64-encoded-signature>
