apiVersion: v1
kind: Secret
metadata:
  name: netbox-webhook-signature
  namespace: eda
type: Opaque
data:
  # base64-encoded signature key that NetBox will use
  signatureKey: ${NETBOX_WEBHOOK_SIGNATURE_KEY}