apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: xai
spec:
  appInfo:
    categories:
      - ai
    documentation: xai/docs
    settings: xai/settings/openapi/eda_oas_xai.eda.nokia.com_appsettings.json
  author: nokia
  description: This application installs the xAI Provider.
  group: xai.eda.nokia.com
  image: ghcr.io/nokia-eda/apps/xai:v7.0.0
  supportedCoreVersions:
    - "v6.0"
  title: xAI
  version: v1
  components:
    - cr:
        path: xai/resources/xai.yaml
    - cr:
        path: xai/resources/openai-embeddings.yaml
