apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-os-creds
  namespace: eda-system
  labels:
    "eda.nokia.com/backup": "true"
data:
  username: YWRtaW4K # base64 encoded
  password: YWRtaW4K # base64 encoded
  user_domain_name: YWRtaW4K # Optional, can also be set in spec; base64 encoded here
  project_name: YWRtaW4K # Optional, can also be set in spec; base64 encoded here
  project_domain_name: YWRtaW4K # Optional, can also be set in spec; base64 encoded here
