apiVersion: appstore.eda.nokia.com/v1
kind: AppInstaller
metadata:
  name: openstack-client-provider
  namespace: eda-system
spec:
  operation: install
  apps:
    - appId: openstack-client-provider.eda.nokia.com
      catalog: eda-catalog-builtin-apps
      version:
        type: alias
        value: latest
