apiVersion: management.eda.nokia.com/v1
kind: GRPCServer
metadata:
  name: grpc-server
  namespace: eda
spec:
  enabled: true
  metadataAuthentication: true
  router: my-router
  routerKind: Router
  services:
    - GNMI
    - GNOI
    - GNSI