apiVersion: management.eda.nokia.com/v1
kind: SSHServer
metadata:
  name: ssh-server
  namespace: eda
spec:
  enablePasswordAuthentication: false
  enabled: true
  router: my-router
  routerKind: Router