apiVersion: appstore.eda.nokia.com/v1
kind: AppInstaller
metadata:
  name: nutanix-plugin
  namespace: eda-system
spec:
  operation: install
  apps:
    - appId: nutanix.eda.nokia.com
      catalog: eda-catalog-builtin-apps
      version:
        type: semver
        value: v0.0.1-beta
