apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: kafka-exporter-install
  namespace: eda-system
spec:
  type: app-installer
  input:
    operation: install
    apps:
      - app: kafka-exporter
        catalog: eda-catalog-builtin-apps
        vendor: nokia
        version:
          type: semver
          value: v3.0.0
