apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eda-gw
  namespace: default
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTP
      port: 8080
      name: web-gw
