authors:
  rdodin:
    name: Roman Dodin
    description: Swagger
    avatar: https://gitlab.com/rdodin/pics/-/wikis/uploads/55adbfe3e2a891510dd2821237b45758/roman_dodin_avatar.webp
  bwallis:
    name: Bruce Wallis
    description: Chief Echidna Officer
    avatar: https://avatars.githubusercontent.com/u/4969068
