authors:
  rdodin:
    name: Roman Dodin
    description: SR Linux PLM
    avatar: https://avatars.githubusercontent.com/u/5679861
  bwallis:
    name: Bruce Wallis
    description: Chief Echidna Officer
    avatar: https://avatars.githubusercontent.com/u/4969068
