apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-k8s-creds
  namespace: eda-system
  labels:
    "eda.nokia.com/backup": "true"
stringData:
  usertoken: "..." # Token that can read Pods, nodes, NADs, and NodeNetworkState
