apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: vmware-plugin
  namespace: eda-system
spec:
  input:
    app: vmware-plugin
    catalog: eda-catalog-builtin-apps
    operation: install
    vendor: nokia
    version:
      type: semver
      value: v2.0.0
  type: app-installer
