apiVersion: fabrics.eda.nokia.com/v1alpha1
kind: Fabric
metadata:
  name: my-nb-ebgp-fabric
  namespace: eda
spec:
  leafs:
    leafNodeSelector:
      - eda.nokia.com/role=leaf
  spines:
    spineNodeSelector:
      - eda.nokia.com/role=spine
  interSwitchLinks:
    linkSelector:
      - eda.nokia.com/role=interSwitch
    poolIPV6: nb-isl-v6
  systemPoolIPV4: nb-systemip-v4
  underlayProtocol:
    bgp:
      asnPool: asn-pool
    protocol:
      - EBGP
  overlayProtocol:
    protocol: EBGP