apiVersion: appstore.eda.nokia.com/v1
kind: AppInstaller
metadata:
  name: gitlab-install
  namespace: eda-system
spec:
  operation: install
  apps:
    - appId: gitlab.eda.nokia.com
      catalog: eda-catalog-builtin-apps
      version:
        type: alias
        value: latest
