apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: openai
spec:
  appInfo:
    categories:
      - ai
    documentation: openai/docs
    settings: openai/settings/openapi/eda_oas_openai.eda.nokia.com_appsettings.json
  author: nokia
  description: This application installs the OpenAI Provider.
  group: openai.eda.nokia.com
  image: ghcr.io/nokia-eda/apps/openai:v6.999.0
  supportedCoreVersions:
    - "v5.0"
  title: OpenAI
  version: v1
  components:
    - cr:
        path: openai/resources/openai.yaml
    - cr:
        path: openai/resources/openai-embeddings.yaml
  supportedEndpoints:
    - "srl:24.10.*"
    - "srl:25.3.*"
    - "srl:25.7.*"
    - "srl:25.10.*"
    - "srl:26.3.*"
    - "sros:24.10.r4+"
    - "sros:25.3.r2+"
    - "sros:25.7.*"
    - "sros:25.10.*"
    - "sros:26.3.*"
    - "eos:4.33.2f:beta"
    - "nxos:10.5.2:alpha"
