apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: openai
spec:
  appInfo:
    categories:
      - ai
    documentation: openai/docs
    settings: openai/settings/openapi/eda_oas_openai.eda.nokia.com_appsettings.json
  author: nokia
  description: This application installs the OpenAI Provider.
  group: openai.eda.nokia.com
  image: ghcr.io/nokia-eda/apps/openai:v7.0.0
  supportedCoreVersions:
    - "v6.0"
  title: OpenAI
  version: v1
  components:
    - cr:
        path: openai/resources/openai.yaml
    - cr:
        path: openai/resources/openai-embeddings.yaml
