apiVersion: influxdb.eda.nokia.com/v1alpha1
kind: Server
metadata:
  name: server1
  namespace: eda
spec:
  url: http://influxdb.example.svc.cluster.local:8086
  org: eda_team
  credentialsSecret: influx-secret
  batchSize: 100
  flushTimer: 10s
  timestampPrecision: milliseconds
  useGzip: false
