apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: tpi
spec:
  appInfo:
    categories:
      - integrations
    documentation: tpi/docs
    settings: tpi/settings/openapi/eda_oas_tpi.eda.nokia.com_appsettings.json
  author: nokia
  description: Import and export EDA objects via TPI (xlsx-based batch processing)
  group: tpi.eda.nokia.com
  image: vno-oci-candidates.repo.cci.nokia.net/vno26/tpi:v0.0.0
  supportedCoreVersions:
    - v5.0
  title: TPI
  version: v1
  components:
    - cr:
        path: tpi/workflows/tpiexport.yaml
    - cr:
        path: tpi/workflows/tpiimport.yaml
    - cr:
        path: tpi/workflows/tpiimportdryrun.yaml
    - cr:
        path: tpi/tpi-manager.yaml
    - crd:
        api:
          expose: readWrite
        path: tpi/crds/tpi.eda.nokia.com_tpiexports.yaml
        schema: tpi/openapiv3/eda_oas_tpi.eda.nokia.com_tpiexports.json
        workflow: true
        ui:
          name: TPI Export
    - crd:
        api:
          expose: readWrite
        path: tpi/crds/tpi.eda.nokia.com_tpiimports.yaml
        schema: tpi/openapiv3/eda_oas_tpi.eda.nokia.com_tpiimports.json
        workflow: true
        ui:
          name: TPI Import
    - crd:
        api:
          expose: readWrite
        path: tpi/crds/tpi.eda.nokia.com_tpifilters.yaml
        schema: tpi/openapiv3/eda_oas_tpi.eda.nokia.com_tpifilters.json
        kubernetes:
          importPolicy: all
          exportPolicy: all
        ui:
          category: TPI
          name: TPI Filter
    - crd:
        api:
          expose: readWrite
        path: tpi/crds/tpi.eda.nokia.com_tpis.yaml
        schema: tpi/openapiv3/eda_oas_tpi.eda.nokia.com_tpis.json
        kubernetes:
          importPolicy: all
          exportPolicy: all
        ui:
          category: TPI
          name: TPI
    - crd:
        api:
          expose: readWrite
        path: tpi/crds/tpi.eda.nokia.com_tpistorages.yaml
        schema: tpi/openapiv3/eda_oas_tpi.eda.nokia.com_tpistorages.json
        kubernetes:
          importPolicy: all
          exportPolicy: all
        ui:
          category: TPI
          name: TPI Storage
    - crd:
        api:
          expose: readWrite
        path: tpi/crds/tpi.eda.nokia.com_tpiimportdryruns.yaml
        schema: tpi/openapiv3/eda_oas_tpi.eda.nokia.com_tpiimportdryruns.json
        workflow: true
        ui:
          name: TPI Import Dry Run
  dependencies:
    - file:
        path: tpi/api/v1/pysrc
    - file:
        path: tpi/api
    - container:
        name: tpiimport
        image: vno-docker-candidates.repo.cci.nokia.net/vno26/tpiimport-image:v0.0
    - container:
        name: tpiimportdryrun
        image: vno-docker-candidates.repo.cci.nokia.net/vno26/tpiimportdryrun-image:v0.0
    - container:
        name: tpiexport
        image: vno-docker-candidates.repo.cci.nokia.net/vno26/tpiexport-image:v0.0
    - container:
        name: tpi-manager
        image: vno-docker-candidates.repo.cci.nokia.net/vno26/tpimanager-image:v0.0
