apiVersion: appstore.eda.nokia.com/v1
kind: AppInstaller
metadata:
  name: influxdb-exporter-install-sized
  namespace: eda-system
spec:
  operation: install
  apps:
    - appId: influxdb.eda.nokia.com
      catalog: eda-catalog-builtin-apps
      version:
        type: alias
        value: latest
      appSettings:
        influxDBExporterCPULimit: "2"
        influxDBExporterMemoryLimit: 2Gi
        influxDBProxyConfig: proxy-config
