apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: gemini
spec:
  appInfo:
    categories:
      - ai
    documentation: gemini/docs
    settings: gemini/settings/openapi/eda_oas_gemini.eda.nokia.com_appsettings.json
  author: nokia
  description: This application installs the Gemini Provider.
  group: gemini.eda.nokia.com
  image: ghcr.io/nokia-eda/apps/gemini:v7.0.0
  supportedCoreVersions:
    - "v6.0"
  title: Gemini
  version: v1
  components:
    - cr:
        path: gemini/resources/gemini.yaml
    - cr:
        path: gemini/resources/openai-embeddings.yaml
