apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: connect-nokia
  namespace: eda-system
spec:
  operation: delete
  apps:
    - app: connect
      catalog: eda-catalog-builtin-apps
      vendor: nokia
      version:
        type: semver
        value: v3.0.0
  type: app-installer
