apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {CERTIFICATE_AUTH_DATA}
    server: {https://FQDN:6443} # should be used for CONNECT_HOST
  name: eda-cluster
contexts:
- context:
    cluster: eda-cluster
    user: eda-cluster
  name: eda-cluster
current-context: eda-cluster
kind: Config
preferences: {}
users:
- name: eda-cluster
  user:
    client-certificate-data: {CLIENT_CERTIFICATE_DATA} # should be used for CONNECT_USERNAME
    client-key-data: {CLIENT_KEY_DATA} # Should be used as CONNECT_PASSWORD