name: Add documentation version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Doc version to add to the branch"
        default: "25.4"
        required: true
        type: string
      alias:
        description: "Set version alias if required (e.g. latest)"
        required: false
        type: string

jobs:
  deploy:
    permissions:
      contents: write # Grants write access so that the workflow can push to the versioned docs branch
      packages: read
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git committers plugin

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docs version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "${{ github.event.inputs.alias }}" ]; then
            bash run.sh build-version "${{ github.event.inputs.version }}" "${{ github.event.inputs.alias }}"
          else
            bash run.sh build-version "${{ github.event.inputs.version }}"
          fi

      - name: Set default docs version
        run: |
          bash run.sh set-default-version --push "${{ github.event.inputs.version }}"
