name: Build and Deploy Versioned Docs

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Documentation version"
        default: "25.4"
        required: true
        type: string
      alias:
        description: "Version alias (e.g. latest or not)"
        required: false
        default: ""
        options:
          - ""
          - "latest"
        type: choice

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      target-branch: ${{ steps.set-target-branch.outputs.target-branch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git committers plugin
          ref: release-${{ github.event.inputs.version }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docs version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "${{ github.event.inputs.alias }}" ]; then
            bash run.sh build-version "${{ github.event.inputs.version }}" "${{ github.event.inputs.alias }}"
          else
            bash run.sh build-version "${{ github.event.inputs.version }}"
          fi

      - name: Set default docs version
        if: ${{ github.event.inputs.alias != '' }}
        run: |
          bash run.sh set-default-version --push "${{ github.event.inputs.version }}"

      - name: Set target branch
        id: set-target-branch
        run: |
          if [ "${{ github.repository }}" != "nokia-eda/docs" ]; then
            echo "target-branch=preview" >> $GITHUB_OUTPUT
          else
            echo "target-branch=main" >> $GITHUB_OUTPUT
          fi

  deploy-docs:
    needs: build
    uses: ./.github/workflows/deploy-docs.yml
    secrets: inherit
    with:
      target-branch: ${{ needs.build.outputs.target-branch }}
