---
name: CICD
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  publish-preview-docs:
    runs-on: ubuntu-24.04
    # do not run on main, only on PRs and other branches
    # publishing to the preview site is not needed on main
    if: ${{ !(github.ref_name == 'main') }}
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    permissions:
      pull-requests: write
      issues: write
      contents: read
      deployments: write
      repository-projects: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docs
        run: bash run.sh build-docs

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        id: wrangler-deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy site --project-name=eda-docs --branch=${{ env.BRANCH_NAME }}

      - name: Add deploy comment to PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const branchName = process.env.BRANCH_NAME.replace(/\./g, '-');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🏗 Preview site deployed to:

              * ${{ steps.wrangler-deploy.outputs.deployment-url }}
              * https://${branchName}.eda-docs.pages.dev`
              })
