---
name: Preview latest docs
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  preview-latest-docs:
    runs-on: ubuntu-24.04
    # do not run on nokia-eda/docs repo
    if: ${{ !(github.repository == 'nokia-eda/docs') }}
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    permissions:
      pull-requests: write
      issues: write
      contents: read
      deployments: write
      repository-projects: read
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docs
        run: bash run.sh build-docs

      - name: User preview branch name if push to main
        if: github.ref == 'refs/heads/main'
        env:
          PREVIEW_BRANCH: ${{ secrets.DOCS_PREVIEW_URL }}
        run: |
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "BRANCH_NAME=${PREVIEW_BRANCH}" >> $GITHUB_ENV
          fi

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        id: wrangler-deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy site --project-name=eda-docs --branch=${{ env.BRANCH_NAME }}

      - name: Add deploy comment to PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const branchName = process.env.BRANCH_NAME.replace(/\./g, '-');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🏗 Preview site deployed to:

              * ${{ steps.wrangler-deploy.outputs.deployment-url }}
              * https://${branchName}.eda-docs.pages.dev`
              })
